### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by xingfeT** [brown/protobuf#12]
luoxing@localhost lisp $make install 

/Users/didi/bin/g++ -std=c++0x -I/local/software/package/protobuf/include -I. -I/Users/didi/include  -c -o enum.o enum.cc enum.cc: 在成员函数‘void google::protobuf::compiler::lisp::EnumGenerator::GenerateDefType(google::protobuf::io::Printer*)’中: enum.cc:90:3: 错误：‘set’在此作用域中尚未声明    set<int> numbers;

**Comment by luoxing91** [comment]
/Users/didi/bin/g++ -std=c++0x -I/local/software/package/protobuf/include -I. -I/Users/didi/include  -c -o enum_field.o enum_field.cc
enum_field.cc: 在成员函数‘virtual void google::protobuf::compiler::lisp::RepeatedEnumFieldGenerator::GenerateMergeFromArray(google::protobuf::io::Printer*) const’中:
enum_field.cc:197:30: 错误：对不完全的类型‘const class google::protobuf::FieldOptions’的非法使用
   if (!descriptor_->options().packed()) {
                              ^
In file included from field.h:36:0,
                 from enum_field.h:36,
                 from enum_field.cc:31:
/usr/local/include/google/protobuf/descriptor.h:98:7: 附注：forward declaration of ‘class google::protobuf::FieldOptions’
 class FieldOptions;

**Comment by brown** [comment]
I cannot reproduce this problem.
