### ISSUE TITLE
Needs Updating for ASDF 3.1 (?)

### ISSUE THREAD

**Issue by senor-hadoop** [brown/protobuf#4]
I just updated to the latest ASDF (for other reasons), and get the following when loading the example in CCL. Not sure if it's ASDF or if there really is a missing package PB.

? (asdf:load-system 'protobuf)
T
? (asdf:load-system 'protobuf-example)
; Warning: No dependency propagating scheme specified for operation class PROTOBUF-SYSTEM::PROTO-TO-LISP.
;          The class needs to be updated for ASDF 3.1 and specify appropriate propagation mixins.
; While executing: #<STANDARD-METHOD INITIALIZE-INSTANCE :BEFORE (ASDF/OPERATION:OPERATION)>, in process listener(1).
Read error between positions 893 and 947 in /Users/snunez/.cache/common-lisp/ccl-1.10-f96-macosx-x64/Users/snunez/src/lisp/protobuf/example/addressbook.lisp.
> Error: There is no package named "PB" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry finding package with name "PB".
> Type :? for other options.

**Comment by brown** [comment]
The error is indicating that protobuf/package.lisp, which defines
the PROTOCOL-BUFFER package with nickname PB, has not
been loaded.  Looks like an error in my asd file or in protobuf.asd.
I regularly run the tests, but have not tried the address book
example code in a while.

For now load protobuf/package.lisp and try again.  I'll fix the
underlying error.  Thanks for the bug report!

Bob

**Comment by senor-hadoop** [comment]
Sadly loading directly doesn't work either:

? (load "~/src/lisp/protobuf/example/package.lisp")
> Error: Cannot SHADOWING-IMPORT "TYPE" from package "TUTORIAL"
> While executing: (:INTERNAL CCL::OPERATION-ON-ALL-SPECS CCL::%DEFINE-PACKAGE), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Ignore attempt to SHADOWING-IMPORT "TYPE" from package "TUTORIAL"
> Type :? for other options.

**Comment by brown** [comment]
I cannot reproduce your problem.

Here is a transcript of me running CCL ... loading protobuf
and protobuf-example.  My version of asdf is 3.1.3.  Do the
same thing.  Somehow protobuf/package.lisp is not being
loaded.  What version of asdf are you using?  Maybe I have
an older version.

Let me know what you find.

Bob



brown <31959>  ccl
;Loading
#P"/usr/local/google/home/brown/software/package/ccl-1.10-r16179/tools/asdf.lx64fsl"...
Welcome to Clozure Common Lisp Version 1.10-RC1-r16169  (LinuxX8664)!

CCL is developed and maintained by Clozure Associates. For more information
about CCL visit http://ccl.clozure.com.  To enquire about Clozure's Common
Lisp
consulting services e-mail info@clozure.com or visit http://www.clozure.com.

? (load-quicklisp)
;Loading #P"/usr/local/google/home/brown/quicklisp/setup.lisp"...
#P"/usr/local/google/home/brown/quicklisp/setup.lisp"
? (load-system 'protobuf)
;Loading
#P"/usr/local/google/home/brown/toe/open-source/protobuf/protobuf.asd"...
;Compiler warnings for
"/usr/local/google/home/brown/toe/open-source/protobuf/protobuf.asd" :
;   In (PERFORM (PROTO-TO-LISP PROTOBUF-SOURCE-FILE)) inside an anonymous
lambda form: Unused lexical variable OUTPUT
;Compiler warnings for
"/usr/local/google/home/brown/toe/open-source/protobuf/protobuf.asd" :
;   In (PERFORM (PROTO-TO-LISP PROTOBUF-SOURCE-FILE)) inside an anonymous
lambda form: Unused lexical variable ERROR-OUTPUT
;Loading
#P"/usr/local/google/home/brown/toe/open-source/base/com.google.base.asd"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/base/package.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/package.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/base/optimize.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/optimize.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/base/syntax.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/syntax.lx64fsl"...
;Compiling "/usr/local/google/home/brown/toe/open-source/base/error.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/error.lx64fsl"...
;Compiling "/usr/local/google/home/brown/toe/open-source/base/type.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/type.lx64fsl"...
;Compiling "/usr/local/google/home/brown/toe/open-source/base/octet.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/octet.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/base/sequence.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/sequence.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/toe/open-source/protobuf/varint/varint.asd"...
;Loading
#P"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/nibbles.asd"...
;Loading
#P"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/trivial-utf-8-20111001-darcs/trivial-utf-8.asd"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/package.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/package.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/types.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/types.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/macro-utils.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/macro-utils.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/vectors.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/vectors.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/streams.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/streams.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/fndb.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/fndb.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/nib-tran.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/nib-tran.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/x86-vm.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/x86-vm.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/x86-64-vm.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/x86-64-vm.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/varint/package.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/varint/package.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/varint/varint.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/varint/varint.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/trivial-utf-8-20111001-darcs/trivial-utf-8.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/trivial-utf-8-20111001-darcs/trivial-utf-8.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/package.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/package.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/protocol-buffer.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/protocol-buffer.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/wire-format.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/wire-format.lx64fsl"...
T
? (load-system 'protobuf-example)
;Loading
#P"/usr/local/google/home/brown/toe/open-source/protobuf/example/protobuf-example.asd"...
; Warning: No dependency propagating scheme specified for operation class
PROTOBUF-SYSTEM::PROTO-TO-LISP.
;          The class needs to be updated for ASDF 3.1 and specify
appropriate propagation mixins.
; While executing: #<STANDARD-METHOD INITIALIZE-INSTANCE :BEFORE
(ASDF/OPERATION:OPERATION)>, in process listener(1).
;Compiling
"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/addressbook.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/addressbook.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/example/package.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/package.lx64fsl"...
;Compiling
"/usr/local/google/home/brown/toe/open-source/protobuf/example/address-book.lisp"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/address-book.lx64fsl"...
T
? (quit)

brown <31960>

brown <31960>

brown <31960>

brown <31960>  ccl
;Loading
#P"/usr/local/google/home/brown/software/package/ccl-1.10-r16179/tools/asdf.lx64fsl"...
Welcome to Clozure Common Lisp Version 1.10-RC1-r16169  (LinuxX8664)!

CCL is developed and maintained by Clozure Associates. For more information
about CCL visit http://ccl.clozure.com.  To enquire about Clozure's Common
Lisp
consulting services e-mail info@clozure.com or visit http://www.clozure.com.

? (load-quicklisp)
;Loading #P"/usr/local/google/home/brown/quicklisp/setup.lisp"...
#P"/usr/local/google/home/brown/quicklisp/setup.lisp"
? (load-system 'protobuf-example)
;Loading
#P"/usr/local/google/home/brown/toe/open-source/protobuf/example/protobuf-example.asd"...
;Loading
#P"/usr/local/google/home/brown/toe/open-source/protobuf/protobuf.asd"...
;Compiler warnings for
"/usr/local/google/home/brown/toe/open-source/protobuf/protobuf.asd" :
;   In (PERFORM (PROTO-TO-LISP PROTOBUF-SOURCE-FILE)) inside an anonymous
lambda form: Unused lexical variable OUTPUT
;Compiler warnings for
"/usr/local/google/home/brown/toe/open-source/protobuf/protobuf.asd" :
;   In (PERFORM (PROTO-TO-LISP PROTOBUF-SOURCE-FILE)) inside an anonymous
lambda form: Unused lexical variable ERROR-OUTPUT
;Loading
#P"/usr/local/google/home/brown/toe/open-source/base/com.google.base.asd"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/package.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/optimize.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/syntax.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/error.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/type.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/octet.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/base/sequence.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/toe/open-source/protobuf/varint/varint.asd"...
;Loading
#P"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/nibbles.asd"...
;Loading
#P"/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/trivial-utf-8-20111001-darcs/trivial-utf-8.asd"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/package.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/types.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/macro-utils.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/vectors.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/streams.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/fndb.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/nib-tran.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/x86-vm.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/nibbles-20150608-git/sbcl-opt/x86-64-vm.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/varint/package.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/varint/varint.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/quicklisp/dists/quicklisp/software/trivial-utf-8-20111001-darcs/trivial-utf-8.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/package.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/protocol-buffer.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/wire-format.lx64fsl"...
; Warning: No dependency propagating scheme specified for operation class
PROTOBUF-SYSTEM::PROTO-TO-LISP.
;          The class needs to be updated for ASDF 3.1 and specify
appropriate propagation mixins.
; While executing: #<STANDARD-METHOD INITIALIZE-INSTANCE :BEFORE
(ASDF/OPERATION:OPERATION)>, in process listener(1).
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/addressbook.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/package.lx64fsl"...
;Loading
#P"/usr/local/google/home/brown/.cache/common-lisp/ccl-1.10-f96-linux-x64/usr/local/google/home/brown/toe/open-source/protobuf/example/address-book.lx64fsl"...
T
? (quit)

brown <31961>

**Comment by senor-hadoop** [comment]
Hmm. Starting with a new CCL image seems to have done the trick. I do it a slightly different way though. In any case it works. Apologies for the false alarm.

? (ql:quickload 'protobuf)
To load "protobuf":
  Load 1 ASDF system:
    protobuf
; Loading "protobuf"
To load "nibbles":
  Install 1 Quicklisp release:
    nibbles
; Fetching #<URL "http://beta.quicklisp.org/archive/nibbles/2014-11-06/nibbles-20141106-git.tgz">
; 20.68KB
==================================================
21,177 bytes in 0.18 seconds (114.78KB/sec)
; Loading "nibbles"
[package nibbles]....................
; Loading "protobuf"
To load "trivial-utf-8":
  Install 1 Quicklisp release:
    trivial-utf-8
; Fetching #<URL "http://beta.quicklisp.org/archive/trivial-utf-8/2011-10-01/trivial-utf-8-20111001-darcs.tgz">
; 5.91KB
==================================================
6,055 bytes in 0.00 seconds (3805.07KB/sec)
; Loading "trivial-utf-8"
[package trivial-utf-8]...........
; Loading "protobuf"
[package varint]..................................
[package protocol-buffer].........................
[package wire-format]...
(PROTOBUF)
? (ql:quickload 'protobuf-example)
To load "protobuf-example":
  Load 1 ASDF system:
    protobuf-example
; Loading "protobuf-example"
..................................................
[package address-book].
(PROTOBUF-EXAMPLE)
